### ISSUE TITLE
Double-check requirements

### ISSUE THREAD

**Issue by pedrorocha-net** [pedrorocha-net/generator-iac#1]
Make sure that we have the following features on the project:
- Based in Gulp
- Scaffolding projects with Yeoman
- Integrated with the ionic-cli
- Browser LiveReload
- Emulator LiveReload
- Sass stylesheets compilation
- HTML, JavaScript and CSS obfuscation and minification
- Automatically inject all your JS sources into index.html
- Handles AngularJS dependency injection annotations
- Icons and Splashscreens support
- generate icon font from svg files
- Cordova plugin management hooks
- Environment Specific Configuration for AngularJS
- Linting JavaScript
- Running unit tests
- Code coverage reporting with istanbul
- Bundled ripple emulator

**Comment by dielduarte** [comment]
we have a problem with ngAnnotate and coffescript : 

https://github.com/olov/ng-annotate/issues/152
https://github.com/olov/ng-annotate/issues/194

**Comment by pedrorocha-net** [comment]
Scope reviewed and issue completed
