### ISSUE TITLE
Convert yeoman command to "iac"

### ISSUE THREAD

**Issue by pedrorocha-net** [pedrorocha-net/generator-iac#2]
Every yeoman generator command available for this project should be inside "iac" namespace. To start it, we need to convert the "m-ionic" commands.

**Comment by dielduarte** [comment]
change name in package.json for 'gerenator-yourcommand', now ready to using "yo iac".
Reference : 
https://github.com/pedrorocha-net/ionic-apps-console/commit/5a4a3581478d968933d84d5d63f930ee5f793579
