### ISSUE TITLE
[META] Change file/folder structure to be feature based

### ISSUE THREAD

**Issue by pedrorocha-net** [pedrorocha-net/generator-iac#3]
Meta issue, as we'll have many sub-tasks here to actually completed this.

We should organize files by what they mean inside the app, not if they are a Service, Controller, etc.
We'll need to upgrade the generators to achieve that.

First of all, we need to determine exactly what those sub-tasks are. Analyze the generator tasks and map here what needs to be upgraded.

**Comment by dielduarte** [comment]
ready, last commit about this :
https://github.com/pedrorocha-net/generator-iac/commit/8ccf680aacb34a1c4907a0c3c9ec77b108aba6aa
